name: polydiff
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.6.4
  - ffmpeg=4.3
  - fontconfig=2.14.1
  - freetype=2.12.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.48.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.4
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.7.3
  - openh264=2.1.1
  - openssl=1.1.1w
  - pcre2=10.42
  - pillow=9.4.0
  - pip=22.3.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.16
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - qt=5.9.7
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.6.3
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.45.3
  - tk=8.6.14
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tornado=6.2
  - typing_extensions=4.3.0
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - carla==0.9.15
      - decorator==5.1.1
      - dictor==0.1.12
      - distro==1.9.0
      - elementpath==1.3.3
      - ephem==4.1.6
      - fonttools==4.38.0
      - kiwisolver==1.4.5
      - networkx==2.2
      - numpy==1.18.4
      - opencv-python==4.2.0.32
      - packaging==24.0
      - psutil==6.1.0
      - py-trees==0.8.3
      - pydot==2.0.0
      - pygame==2.6.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - shapely==1.6.4.post2
      - tabulate==0.9.0
      - xmlschema==1.0.18
